version: "3.6"

networks:
  default:
    internal: true

services:
  app:
    build:
      context: .
    image: worm:latest
    build: .
    environment:
      MAX_DEPTH: 10
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    volumes:
    - type: tmpfs
      target: /tmp
      tmpfs:
        size: 4194304
