#!/bin/sh

[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
[ -d /home ] || mkdir /home

echo 'root:x:0:0:root:/root:/bin/sh' > /etc/passwd
echo 'root:x:0:' > /etc/group
chmod 644 /etc/passwd
chmod 644 /etc/group

adduser user --disabled-password
addgroup user
addgroup user user

chown -R root:root /
chmod 700 -R /root
chmod go-rw flag.txt
chown user:user /home/user
chmod 777 /home/user

mkdir -p /var/lock
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc
mount -t efivarfs efivarfs /sys/firmware/efi/efivars

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

______ _     _          _           _                                        _             _           
| ___ \ |   (_)        ( )         | |                                      | |           (_)          
| |_/ / |__  _ ______ _|/ ___   ___| | __ ___   _____ _ __ _   _    ___ ___ | | ___  _ __  _  ___  ___ 
|    /| '_ \| |_  / _' | / __| / __| |/ _' \ \ / / _ \ '__| | | |  / __/ _ \| |/ _ \| '_ \| |/ _ \/ __|
| |\ \| | | | |/ / (_| | \__ \ \__ \ | (_| |\ V /  __/ |  | |_| | | (_| (_) | | (_) | | | | |  __/\__ \ 
\_| \_|_| |_|_/___\__,_| |___/ |___/_|\__,_| \_/ \___|_|   \__, |  \___\___/|_|\___/|_| |_|_|\___||___/
                                                            __/ |                                      
                                                           |___/

This is a government's monitoring system.


!

exec su user
exec /bin/sh
